version: '3'
services:
  app:
    container_name: freelancer_now
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/app
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    expose:
      - '3000'
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - freelancer-now
      - db-freelancer
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - freelancer_now_data:/var/lib/postgresql/data
    networks:
      - db-freelancer
volumes:
  freelancer_now_data:
networks: 
  freelancer-now: 
    external: true
  db-freelancer:
    external: false